name: CI

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  test:
    name: (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        otp: [21.3.8.1, 22.1, 22.2]
        elixir: [1.7.1, 1.8.1, 1.9.1]
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Formatted
      if: matrix.elixir != '1.7.x'
      run: mix format --check-formatted
    - name: Run Tests
      run: mix test --trace
    - name: Coverage
      if: matrix.elixir == '1.9.1' && matrix.otp == '22.2'
      run: mix coveralls.github
